framework:
  mailer:
    dsn: "%env(MAILER_DSN)%"
    envelope:
      sender: "webmaster@madatransport.com"
      #recipients: ["foo@example.com", "bar@example.com"]
    headers:
      From: "Webmaster <lalaina@example.com>"
      #Bcc: "baz@example.com"
      X-Custom-Header: "foobar"
