framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      # async: '%env(MESSENGER_TRANSPORT_DSN)%'
      failed: "doctrine://default?queue_name=failed"
      sync: "%env(MESSENGER_TRANSPORT_DSN)%"
      #sync: "in-memory://"

    routing:
      # Route your messages to the transports
      'Domain\Utils\Attributes\MessageInterface': sync

    default_bus: command.bus

    buses:
      command.bus:
        middleware:
          - Infrastructure\Middleware\PublishEventMiddleware
      query.bus:
      event.bus:
        default_middleware: allow_no_handlers
# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
