services:
  _defaults:
    autowire: true
    autoconfigure: true
  Domain\:
    resource: "../../src/Domain"

  #in case of multiple injection
  Domain\Utils\Event\EventManagerInterface: '@Infrastructure\Service\Event\EventManager'
