version: "3.3"

services:
  maildev:
    image: maildev/maildev
    restart: always
    ports:
      - 1080:1080
      - 1025:1025
  rabbitmq:
    image: rabbitmq:management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672

  userManagement:
    build:
      context: ../
      dockerfile: ./user-management/Dockerfile
    image: lalaina/user_management
    restart: always
    volumes:
      - ../user-management:/var/www
    ports:
      - 8101:80
    environment:
      - MAILER_DSN=smtp://maildev:1025

  kongGateway:
    image: kong/kong-gateway
    volumes:
      - ../kong/:/kong/declarative
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=../kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8443:8443
      - 8444:8444
